version: '3.9'

services:
  node_app:
    container_name: node_app
    build: .
    image: mateus/platform_app
    ports:
      - "8080:8080"
    environment:
      - MYSQL_DB=apice
      - MYSQL_USER=meu-usuario
      - MYSQL_PASSWORD=minha-senha
      - MYSQL_HOST=node_db
    depends_on:
      - node_db
    restart: always

  node_db:
    container_name: node_db
    image: mysql:8
    ports:
      - "3307:3307"
    environment:
      - MYSQL_ROOT_PASSWORD=minha-senha
      - MYSQL_DATABASE=apice
      - MYSQL_USER=meu-usuario
      - MYSQL_PASSWORD=minha-senha
    volumes:
      - node_db_data:/var/lib/mysql

volumes:
  node_db_data: {}

